import 'package:envied/envied.dart';

part 'env.g.dart';

/// Application environment configuration
/// Generated by envied_generator
/// 
/// This class provides secure access to environment variables including:
/// - Supabase URL and anonymous key for database access
/// - Gemini API key for AI chat functionality
/// - Sentry DSN for crash reporting
/// - Application environment (development/staging/production)
@Envied(path: '.env')
abstract class Env {
  /// Supabase project URL
  @EnviedField(varName: 'SUPABASE_URL')
  static const String supabaseUrl = _Env.supabaseUrl;

  /// Supabase anonymous key for public access
  @EnviedField(varName: 'SUPABASE_ANON_KEY')
  static const String supabaseAnonKey = _Env.supabaseAnonKey;

  /// Gemini API key for AI chat functionality
  @EnviedField(varName: 'GEMINI_API_KEY')
  static const String geminiApiKey = _Env.geminiApiKey;

  /// Kilo Code API key for secondary AI fallback
  @EnviedField(varName: 'KILOCODE_API_KEY')
  static const String kilocodeApiKey = _Env.kilocodeApiKey;

  /// Sentry DSN for crash reporting
  @EnviedField(varName: 'SENTRY_DSN')
  static const String sentryDsn = _Env.sentryDsn;

  /// Application environment (development, staging, production)
  @EnviedField(varName: 'APP_ENV')
  static const String appEnv = _Env.appEnv;

  /// Optional: Custom API base URL
  @EnviedField(varName: 'API_BASE_URL', defaultValue: '')
  static const String apiBaseUrl = _Env.apiBaseUrl;

  /// Check if running in production environment
  static bool get isProduction => appEnv == 'production';

  /// Check if running in development environment
  static bool get isDevelopment => appEnv == 'development';

  /// Check if running in staging environment
  static bool get isStaging => appEnv == 'staging';
}
